#!/bin/bash
# Specify jobname:
#SBATCH --job-name=dos1
# Specify the number of nodes and the number of CPU's (tasks) per node:
#SBATCH --nodes=2 --ntasks-per-node=16
# Specify account. 
#SBATCH --account=ln0003k
# The maximum time allowed for the job, in hh:mm:ss
#SBATCH --time=05:00:00
#SBATCH --mem-per-cpu=3800M
#SBATCH --exclusive


## Set up job environment    
ulimit -l unlimited
ulimit -s unlimited
ulimit -m unlimited
source /cluster/bin/jobsetup
module load vasp

## Run command 
mpirun ~olem/fm4111/bin/vasp_std
